name:  Deploy website on push

on:
  push:
    branches:
      - test

jobs:
  dependencies-install:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: dependencies-php-composer-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2.34
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          server: 104.198.134.0
          port: 22
          username: prohab
          ssh_private_key: ${{secrets.SFTP_SSH_PRIVATE_KEY}}
          remote_path: /mnt/data/aplicaciones/Prueba/recepcion-cm-api/